name: Wails build

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          { name: wailsTest, platform: linux/amd64 , os: ubuntu-latest },
          { name: wailsTest, platform: linux/amd64 , os: debian-latest },
          { name: wailsTest, platform: linux/amd64 , os: centos-latest },
          { name: wailsTest, platform: linux/amd64 , os: fedora-latest },
          { name: wailsTest, platform: linux/arm64 , os: ubuntu-latest },
          { name: wailsTest, platform: linux/arm64 , os: debian-latest },
          { name: wailsTest, platform: linux/arm64 , os: centos-latest },
          { name: wailsTest, platform: linux/arm64 , os: fedora-latest },
          { name: wailsTest, platform: linux/386 , os: ubuntu-latest },
          { name: wailsTest, platform: linux/386 , os: debian-latest },
          { name: wailsTest, platform: linux/386 , os: centos-latest },
          { name: wailsTest, platform: linux/386 , os: fedora-latest },
          { name: wailsTest, platform: linux/amd64 , os: ubuntu-latest },
          { name: wailsTest, platform: linux/amd64 , os: debian-latest },
          { name: wailsTest, platform: linux/amd64 , os: centos-latest },
          { name: wailsTest, platform: linux/amd64 , os: fedora-latest },
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}